### ISSUE TITLE
Copy URL button doesn't work in mobile/desktop Safari

### ISSUE THREAD

**Issue by Conway** [arcanis/secretsanta#31]
When attempting to click/tap "Copy Secret Link" on either desktop or mobile Safari, this error is thrown:

`NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

I can't think of any setting I have on that would prevent the copy/paste from working, and tried to fix it myself, but couldn't get it running locally. I understand if this is a `wontfix` given Safari's lower usage rates, but figured it was worth reporting.

**Comment by arcanis** [comment]
I think it's because Safari doesn't link async functions when calling `navigator.clipboard.writeText` from within click handlers - it loses the information that the function was initially triggered by a user interaction, and rejects the call.

The fix would be to generate the links before the user clicks on the button, but it's not entirely trivial 🤔

**Comment by arcanis** [comment]
I think I fixed it with [2e9d8c3](https://github.com/arcanis/secretsanta/commit/2e9d8c338bc206d6ad0bdd48fe993f1e39f80436) ✅
